Data_Check/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views

urlpatterns = [
    path("index/", views.index),

    #用户管理
    path("user/", views.user),
    path("user_add/", views.user_add),
    path("user_del/", views.user_del),
    #正则表达式传递参数
    path("user/<int:nid>/edit/", views.user_edit),

    path("depart/", views.depart),
    path("depart/add/", views.depart_add),
    path("depart/del/", views.depart_del),

    #正则表达式传递参数
    path("depart/<int:nid>/edit/", views.depart_edit),

    #靓号
    path("number/", views.number),
    path("pretty_add/", views.pretty_add),
    path("pretty/<int:nid>/edit/", views.pretty_edit),
    path("pretty/<int:nid>/del/", views.pretty_del)
]

app01/models.py
from typing import Any
from django.db import models
from django.utils import timezone
from datetime import datetime
# Create your models here.




class UserInfo(models.Model):
    """用户表"""
    name = models.CharField(verbose_name="姓名",max_length=32)
    password = models.CharField(verbose_name="密码",max_length=64)
    age = models.IntegerField(verbose_name="年龄",default=0)
    account = models.DecimalField(verbose_name="账户余额",max_digits=10,decimal_places=2,default=0)
    create_time = models.DateTimeField(verbose_name="入职时间")   #default=timezone.now ,default=datetime.now()


    #有关联的
    # -to 与哪张表关联
    # -to_field 与表中的列关联
    #生成数据列 depart_id
    

    #1.部门id置空
    # on_delete=models.CASCADE,null=True,blank=True 
    # 2.部门删除;
    # on_delete=models.CASCADE删除用户 
    depart = models.ForeignKey(verbose_name='部门',to="Department",to_field="id",on_delete=models.SET_NULL,null=True,blank=True)

    gender_choices = (
        (1,"男"),
        (2,"女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别",choices=gender_choices)



class Department(models.Model):
    """"部门表"""
    title = models.CharField(verbose_name="部门",max_length=32)

    #返回对象
    def __str__(self):
        return self.title

class Prettynumber(models.Model):
    """号码池"""
    phone = models.CharField(verbose_name="手机号",max_length=11)
    price = models.IntegerField(verbose_name="价格",default=0)


    level_choices = (
        (1,"1级用户"),  
        (2,"2级用户"),
        (3,"3级用户"),
        (4,"4级用户"),
        )
    level = models.SmallIntegerField(verbose_name="等级",choices=level_choices)

    status_choices = (
        (1,"占用"),
        (2,"未占用"),
    )
    status = models.SmallIntegerField(verbose_name="状态",choices=status_choices)
    
    #返回对象
    def __str__(self):
        return self.phone

app01/views.py
from django.shortcuts import render ,HttpResponse,redirect
from .models import UserInfo,Department,Prettynumber
from django import forms
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from app01.utils.pagination import Pagination

def index(request):
    return HttpResponse("Hello World")


def user(request):
    #获取数据库中的所有用户信息
    queryset = UserInfo.objects.all()

    page_object = Pagination(request,queryset)

    context = {

        "queryset":page_object.page_queryset,#分完页的数据
        "page_string":page_object.html() #页码
    }

    return render(request,"user.html",context)

class UserModelForm(forms.ModelForm):

    #判断输入字符长度
    name = forms.CharField(label="姓名",max_length=10)
    
    #input框定义样式
    class Meta:
        model = UserInfo
        fields = ['name','password','age','account','create_time','gender','depart']

    def __init__(self,*args,**kwarges):
        super().__init__(*args,**kwarges)
        for name,field in self.fields.items():
            field.widget.attrs = {"class":"form-control"}

def user_add(request):
    #添加用户
    if request.method == "GET":
        form = UserModelForm()
        return render(request,"user_add.html",{"form":form})

    #post校验
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        print(form.cleaned_data)

        #保存数据
        form.save()
        return redirect("/user/")
    
    #校验失败
    return render(request,"user_add.html",{"form":form})


def user_del(request):
    #删除用户信息
    nid = request.GET.get("nid")
    UserInfo.objects.filter(id=nid).delete()
    return redirect("/user/")

def user_edit(request,nid):
    #修改用户信息
    row_obj = UserInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        form = UserModelForm(instance=row_obj)
        return render(request,"user_edit.html",{"form":form})
        
    form = UserModelForm(data=request.POST,instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect("/user/")
    #校验失败
    return render(request,"user_add.html",{"form":form})

#部门
def depart(request):
    #获取数据库中的所有部门信息
    queryset = Department.objects.all()
    
    page_object = Pagination(request,queryset)

    context = {

        "queryset":page_object.page_queryset,#分完页的数据
        "page_string":page_object.html() #页码
    }



    return render(request,"depart.html",context)


def depart_add(request):
    if request.method == "GET":
        return render(request,"depart_add.html")
    
    #添加部门
    title = request.POST.get("title")
    Department.objects.create(title=title)

    #重定向回部门列表
    return redirect("/depart/")


def depart_del(request):
    #删除ID部门
    nid = request.GET.get("nid")
    Department.objects.filter(id=nid).delete()
    return redirect("/depart/")


def depart_edit(request,nid):
    #编辑部门
    #根据nid 获取数据第一条
    if request.method == "GET":
        row_obj = Department.objects.filter(id=nid).first()
        return render(request,"depart_edit.html",{"row_obj":row_obj})
    
    #修改部门
    title = request.POST.get("title")
    Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/")



#靓号
def number(request):
    #号码列表


    data_dict={}
    search_data = request.GET.get("q",'')
    
    print(search_data)

    if search_data:
        data_dict["phone__contains"] = search_data

    queryset = Prettynumber.objects.filter(**data_dict).order_by("-level")
    
    page_object = Pagination(request,queryset)

    context = {
        "search_data":search_data,

        "queryset":page_object.page_queryset,#分完页的数据
        "page_string":page_object.html() #页码
    }

    return render(request,"number.html",context)




class PhoneModelForm(forms.ModelForm):

    #判断输入格式
    phone = forms.CharField(
        label="手机号",
        validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号格式错误')],
    )

    #input框定义样式
    class Meta:
        model = Prettynumber
        fields = ['phone','price','level','status']

    def __init__(self,*args,**kwarges):
        super().__init__(*args,**kwarges)
        for name,field in self.fields.items():
            field.widget.attrs = {"class":"form-control"}
    # 钩子方法校验
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        #判断手机号是否重复
        if Prettynumber.objects.filter(phone=phone).exists():
            raise ValidationError("手机号已存在")
        return phone

#新建号码
def pretty_add(request):
    if request.method == "GET":
        form = PhoneModelForm
        return render(request,"number_add.html",{"form":form})
    
    #新建号码
    form = PhoneModelForm(request.POST)
    if form.is_valid():
        form.save()
        return redirect("/number/")
    return render(request,"number_add.html",{"form":form})




class PhoneeditModelForm(forms.ModelForm):

    #判断输入格式
    phone = forms.CharField(
        label="手机号",
        validators=[RegexValidator(r'^1[3-9]\d{9}$', '手机号格式错误')],
    )

    #input框定义样式
    class Meta:
        model = Prettynumber
        fields = ['phone','price','level','status']

    def __init__(self,*args,**kwarges):
        super().__init__(*args,**kwarges)
        for name,field in self.fields.items():
            field.widget.attrs = {"class":"form-control"}
    # 钩子方法校验
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        #判断手机号是否重复

        #排查自身以外的id
        if Prettynumber.objects.exclude(id=self.instance.pk).filter(phone=phone).exists():
            raise ValidationError("手机号已存在")
        return phone



#编辑号码
def pretty_edit(request,nid):

    #获取表单
    row_obj = Prettynumber.objects.filter(id=nid).first()

    if request.method == "GET":
        form = PhoneeditModelForm(instance=row_obj)
        return render(request,"number_edit.html",{"form":form})
    #编辑号码
    form = PhoneeditModelForm(request.POST,instance=row_obj)
    if form.is_valid():
        form.save()
        return redirect("/number/")
    #校验失败
    return render(request,"number_edit.html",{"form":form})


#删除号码
def pretty_del(request,nid):
    Prettynumber.objects.filter(id=nid).delete()
    return redirect("/number/")

app01/templates/depart.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div style="margin-bottom: 1%;">
        <a class="btn btn-primary" href="/depart/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>    
            新建部门</a>
    </div>
    <div class="bs-example" data-example-id="panel-without-body-with-table">
        <div class="panel panel-default">

        
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            部门列表</div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>名称</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in queryset %}
                    <tr>
                        <td>{{obj.id}}</td>
                        <td>{{obj.title}}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/depart/{{obj.id}}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/depart/del/?nid={{obj.id}}">删除</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <ul class="pagination" style="float: left;">
        {{page_string}}
    </ul>
</div>

{% endblock %}

app01/templates/depart_add.html
{% extends "layout.html" %}

{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建部门 </h3>
            </div>
            <div class="panel-body">

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control" placeholder="标题" name="title" />
                    </div>
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>
    
{% endblock %}

app01/templates/depart_edit.html
{% extends "layout.html" %}

{% block content %}


    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 修改部门 </h3>
            </div>
            <div class="panel-body">

                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>标题</label>
                        <input type="text" class="form-control" placeholder="标题" name="title" value="{{row_obj.title}}" />
                    </div>
                    <button type="submit" class="btn btn-primary">提 交</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

app01/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    <style>
        .navbar{
            border-radius: 0;
        }
    </style>
    {% block css %}{% endblock %}

</head>

<body>

<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">用户管理系统</a>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/">部门管理</a></li>
                <li><a href="/user/">用户管理</a></li>
                <li><a href="/number/">号码管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="#">登录</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">xiaoyu<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div>
    {% block content %}{% endblock %}
</div>

    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
    {% block js %}{% endblock %}
</body>

</html>

app01/templates/number.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">

        <div style="margin-bottom: 1%;"class="clearfix">
            <a class="btn btn-primary" href="/pretty_add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>    
                新建靓号
            </a>
            <div style="float: right; width: 30%;" s>
                <form method="get">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="搜索" value="{{search_data}}">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">
                                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                            </button>
                        </span>
                    </div>
                </form>

            </div>

            <dev class="panel panel-default">
                <div class="panel-heading" style=" margin-top: 2%;">
                    <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    号码池
                </div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>phone</th>
                            <th>价格</th>
                            <th>级别</th>
                            <th>状态</th>
                            <th>操作</th>
                    </thead>
                    <tbody>
                        {% for obj in queryset %}
                        <tr>
                            <td>{{obj.id}}</td>
                            <td>{{obj.phone}}</td>
                            <td>{{obj.price}}</td>
                            <td>{{obj.get_level_display}}</td> 
                            <td>{{obj.get_status_display}}</td>
                            <!-- get_ * _display  获取id对应的信息--> 
                            <td>
                                <a class="btn btn-primary btn-xs" href="/pretty/{{obj.id}}/edit/">编辑</a>
                                <a class="btn btn-danger btn-xs" href="/pretty/{{obj.id}}/del/">删除</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </dev>
        </div>
        <div class="clearfix">
            <ul class="pagination" style="float: left;">
                {{page_string}}
            </ul>
        </div>    
    </div>

{% endblock %}

app01/templates/number_add.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"> 新建号码 </h3>
        </div>
        <div class="panel-body">

            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group" style="margin-top: 1%;" >
                    <label>{{field.label}}</label>
                    {{field}}
                    <span style="color: red;">{{field.errors.0}}</span>
                {% endfor %}
                <button type="submit" class="btn btn-primary" style="margin-top: 1%;">提 交</button>

            </form>
        </div>
    </div>
</div> 

{% endblock %}

app01/templates/number_edit.html
{% extends "layout.html" %}

{% block content %}

    
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 编辑号码 </h3>
            </div>
            <div class="panel-body">

                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group" style="margin-top: 1%;" >
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color: red;">{{field.errors.0}}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="margin-top: 1%;">提 交</button>

                </form>
            </div>
        </div>
    </div>    


{% endblock %}

app01/templates/user.html
{% extends "layout.html" %}

{% block content %}
<div class="container">
    <div style="margin-bottom: 1%;">
        <a class="btn btn-primary" href="/user_add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>    
            新建用户</a>
    </div>
    <div class="bs-example" data-example-id="panel-without-body-with-table">
        <div class="panel panel-default">

        
        <div class="panel-heading">
            <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
            用户列表</div>

            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>姓名</th>
                        <th>密码</th>
                        <th>年龄</th>
                        <th>余额</th>
                        <th>入职时间</th>
                        <th>性别</th>
                        <th>部门</th>
                        <th>操作</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in queryset %}
                    <tr>
                        <td>{{obj.id}}</td>
                        <td>{{obj.name}}</td>
                        <td>{{obj.password}}</td>
                        <td>{{obj.age}}</td>
                        <td>{{obj.account}}</td>
                        <td>{{obj.create_time|date:"Y-m-d H:i:s"}}</td>
                        <td>{{obj.get_gender_display}}</td>
                        <td>{{obj.depart.title}}</td>

                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{obj.id}}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user_del/?nid={{obj.id}}">删除</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <ul class="pagination" style="float: left;">
        {{page_string}}
    </ul>
</div>

{% endblock %}

app01/templates/user_add.html
{% extends "layout.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css' %}">
{% endblock %}


{% block content %}

    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建用户 </h3>
            </div>
            <div class="panel-body">

                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group" style="margin-top: 1%;" >
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color: red;">{{field.errors.0}}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="margin-top: 1%;">提 交</button>

                </form>
            </div>
        </div>
    </div>    


{% endblock %}

{% block js %}
    <script src="{% static 'plugins/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap-datepicker/dist/loacles/bootstrap-datepicker.zh-CN.min.js' %}"></script>
    <script>
        $(function () {
            $('#id_create_time').datepicker({
                language: 'zh-CN',
                autoclose: true,
                format: 'yyyy-mm-dd',
                startDate: '0'
            });
        })
    </script>
{% endblock %}

app01/templates/user_edit.html
{% extends "layout.html" %}

{% block content %}

    
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> 新建用户 </h3>
            </div>
            <div class="panel-body">

                <form method="post" novalidate>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group" style="margin-top: 1%;" >
                        <label>{{field.label}}</label>
                        {{field}}
                        <span style="color: red;">{{field.errors.0}}</span>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary" style="margin-top: 1%;">提 交</button>

                </form>
            </div>
        </div>
    </div>    


{% endblock %}